## Eksamensvideoer AU Smartlearning




___  
___  
___

#### Konverter eksamensopgaven til Word
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270313506' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


<a name="smartau2017_6"></a>



___  
___  
___

#### Eksamen statistik AU Smartlearning 4 timer 2017 6
[2017 6 Eksamensopgave](https://www.dropbox.com/s/dlgt1hnh6wu4aja/Statistik%20eksamensopgave%20juni%202017%20opgave%202.pdf?dl=1)
[2017 6 Løsningsforslag](https://www.dropbox.com/s/s0fl0lg2i2zk2hh/Eksamen%202017%20juni%20opgave%202%20L%C3%98SNING.docx?dl=1)

##### Opgave 2.1 Normalfraktildiagram
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/261471273' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 2.2 Test varians
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/261478912' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 2.3 Test Middel
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/261478966' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 2.4 Test ens varianser
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/261479020' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 2.5 Test to middelværdier
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/261479100' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 2.6 Sandsynlighed normalfordelingen
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/261479159' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 2.7 Sandsynlighed normalfordelingen
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/261471445' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

<a name="smartau2016_1"></a>



___  
___  
___ 


#### Eksamen statistik 4 timer 2016 1  
[2016 1 Opgave](https://www.dropbox.com/s/t1h9o0xnutneavu/AU%20Statistik%20eksamensopgave%20-%20januar%202016.pdf?dl=1)  

[2016 1 Løsningsforslag](https://www.dropbox.com/s/vk2igqyofts6fes/AU%20Statistik%20eksamensopgave%20-%20januar%202016%20l%C3%B8sningsforslag.docx?dl=1)



##### AU januar 2016 Opgave 1.1
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270309969' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>



##### AU januar 2016 Opgave 1.2
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270310431' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>




##### AU januar 2016 Opgave 1.3
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270310886' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>




##### AU januar 2016 Opgave 1.4
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270311020' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>






##### AU januar 2016 Opgave 1.5
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270311217' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>




##### AU januar 2016 Opgave 2.1 og 2.2
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270311300' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>





##### AU januar 2016 Opgave 3.1
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270311591' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>





##### AU januar 2016 Opgave 3.2
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270311802' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>




##### AU januar 2016 Opgave 3.3
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270312269' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>





##### AU januar 2016 Opgave 3.4
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270312695' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>





##### AU januar 2016 Opgave 4.1 og 4.2
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270312916' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>







<a name="smartau2015_8"></a>



___  
___  
___  

#### Eksamen statistik 4 timer 2015 6 
[2015 6 Opgave](https://www.dropbox.com/s/lpyp894as98ho11/Smartlearning%20AU%202015%206.pdf?dl=1)
[2015 6 Løsningsforslag](https://www.dropbox.com/s/kf4avnc43qpz20d/2015%206%20AU%20SMART%20Vejledende.docx?dl=1)

##### Opgave 1.1 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/269192191' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 1.2 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/269192249' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 1.3 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/269192324' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 1.4 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/269192388' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>



##### Opgave 1.5 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/269192472' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>




##### Opgave 1.6 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/267807615' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>





##### Opgave 1.7 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/270313669' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>



##### Opgave 2.1 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/267809477' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>







##### Opgave 2.2 og 2.3 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/267809805' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>







##### Opgave 3.1 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/267892434' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>




##### Opgave 3.2 og 3.3 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/267810285' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>




##### Opgave 3.4 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/267689590' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>



##### Opgave 4.1 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/267684958' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>




##### Opgave 4.2 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/267685056' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>





##### Opgave 4.3 Eksamen AU statistik 4 timer 2015 6
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/267689528' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>



