## Eksamensvideoer

<a name="2017_9_5"></a>



___  
___  
___  

#### Eksamen statistik 2 timer 2017 9 5 
[2017 9 5 Opgave](https://www.dropbox.com/s/3gd6mcocowe8glq/2017%209%20Statistik%20Fin.pdf?dl=1)
[2017 9 5 Data](https://www.dropbox.com/s/y4p8j90wjbzhtb3/2017%209%20statistik%20Data%202.RE.xlsx?dl=1)
[2017 9 5 Løsningsforslag](https://www.dropbox.com/s/wruqocv7g0fvkob/2017%209%20Statistik%20Fin%20opg%201%20og%203%20l%C3%B8sning%20skabelon%20Freestat%20.docx?dl=1)

##### Opgave 1 1 Normalfraktildiagram
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/263814242' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 1 2 Test middel
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/263814353' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 1 3 Varianshomogenitet
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/263814326' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 1 4 Test af 2 middelværdier
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/263814384' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 1 5 Konfidensinterval for forskellen af middelværdier
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/263814294' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 3 1 Test af andel
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/263814257' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 3 2 Konfidensinterval for middelværdi
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/263814415' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


___  
___  
___  

<a name="2016_8_10"></a>



___  
___  
___  

#### Eksamen statistik 2 timer 2016 8 10
[2016 8 10 Opgave](https://drive.google.com/uc?export=download&id=0B1E7VnhxsDMlTy1NVjFBMDRLZFk)
[2016 8 10 Data](https://drive.google.com/uc?export=download&id=0B1E7VnhxsDMlcVdQUVFjUEp2SUE)
[2016 8 10 Løsningsforslag](https://drive.google.com/uc?export=download&id=0B1E7VnhxsDMlQnNjMk9XZDZKWUU)


##### Opgave 1 Lineær regression
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/226381571' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 2 Andele
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/226377107' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 3 Middelværdier
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/226376881' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 4 Teori KI, punktestimat, testniveau
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/226373724' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


<a name="2015_8_7"></a>


  
___  
___  
___  
  
<a name="2015_8_7"></a>



___  
___  
___  
  
#### Eksamen statistik 2 timer 2015 8 7
[2015 8 7 Opgave](https://www.dropbox.com/s/dwbpp3ykq17tbvb/2015%208%207%201.reeksamen.pdf?dl=1)
[2015 8 7 Data](https://www.dropbox.com/s/45d1xkhjp3c0owh/2015%208%207%20Data.xlsx?dl=1)
[2015 8 7 Løsningsforslag](https://www.dropbox.com/s/9nhbc21yth3si6o/2015%208%207%20Freestat%20skabelon%20l%C3%B8sning.docx?dl=1)

##### Opgave 1.1  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266054859' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 1.2  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266054899' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 1.3  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266054921' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 1.4  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266054930' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>



##### Opgave 1.5  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266054963' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 2.1 og 2.2  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266054985' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 2.3   
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266055061' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 3.1   
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266055117' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 3.2  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266055181' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 3.3  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/266055230' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

  



  
___  
___  
___  
  

  
  
<a name="2015_3_4"></a>



___  
___  
___  
  
#### Eksamen statistik 2 timer 2015 3 4  
[2015 3 4 Opgave](https://drive.google.com/file/d/0B1E7VnhxsDMlLVBMek5kWEhRZlU/view?usp=sharing)
[2015 3 4 Data](https://drive.google.com/file/d/0B1E7VnhxsDMlX0p3Qk8wWlNxM28/view?usp=sharing)
[2015 3 4 Løsningsforslag](https://drive.google.com/file/d/0B1E7VnhxsDMlWXNWTW55Sk94RDA/view?usp=sharing)


##### Opgave 1 lineær regression  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/226381565' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Opgave 2 Test af 2 middelværdier  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/226381328' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 3 KI andel og middel, test af middel  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/226381302' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Opgave 4 2 Andele  
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/226379835' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


