### Videoer Quiz

##### Quiz Deskriptiv statistik Realkredit sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/255072273' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz Deskriptiv statistik Diamanter DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/238797725' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz 1 middelværdi Realkredit sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/253815545' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz 1 middelværdi Dow Jones DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/237380053' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz normalfordeling sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/257601727' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz 1 andel sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/255060479' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz 1 andel OMX DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/238859008' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz 2 andele Realkredit sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/257599882' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>


##### Quiz 2 middelværdier Realkredit sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/255087704' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz 2 middelværdier Pooled t-test Dow Jones DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/238795164' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz korrelation Realkredit sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/256091877' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz simpel lineær regression Realkredit sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/256214603' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz Multipel lineær regression Bank DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/238798156' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz Binomialfordeling sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/256068376' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz Poissonfordelingen sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/256069461' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz den hypergeometriskefordeling sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/256081631' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz Chi i anden test Ejendomme DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/238790484' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>

##### Quiz ANOVA Realkredit sc DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/256079739' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>









##### Quiz Multipel lineær regression Bank DEMO video
<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://player.vimeo.com/video/238790484' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>
